package fuck.system.vpn.servers.server;

import fuck.system.vpn.R

object ServerFlag
{
    fun getFlag(countryCode: String?): Int {
        return flagMap[countryCode] ?: R.drawable.flag_xx
    }

    fun getCountry(countryCode: String?): String {
        return countryNames[countryCode] ?: "Unknown"
    }

    val countryNames = mapOf(
        "ad" to "Andorra",
        "ae" to "United Arab Emirates",
        "af" to "Afghanistan",
        "ag" to "Antigua and Barbuda",
        "ai" to "Anguilla",
        "al" to "Albania",
        "am" to "Armenia",
        "ao" to "Angola",
        "aq" to "Antarctica",
        "ar" to "Argentina",
        "as" to "American Samoa",
        "at" to "Austria",
        "au" to "Australia",
        "aw" to "Aruba",
        "ax" to "Åland Islands",
        "az" to "Azerbaijan",
        "ba" to "Bosnia and Herzegovina",
        "bb" to "Barbados",
        "bd" to "Bangladesh",
        "be" to "Belgium",
        "bf" to "Burkina Faso",
        "bg" to "Bulgaria",
        "bh" to "Bahrain",
        "bi" to "Burundi",
        "bj" to "Benin",
        "bl" to "Saint Barthélemy",
        "bm" to "Bermuda",
        "bn" to "Brunei",
        "bo" to "Bolivia",
        "bq" to "Caribbean Netherlands",
        "br" to "Brazil",
        "bs" to "Bahamas",
        "bt" to "Bhutan",
        "bv" to "Bouvet Island",
        "bw" to "Botswana",
        "by" to "Belarus",
        "bz" to "Belize",
        "ca" to "Canada",
        "cc" to "Cocos (Keeling) Islands",
        "cd" to "Congo (DRC)",
        "cf" to "Central African Republic",
        "cg" to "Congo (Republic)",
        "ch" to "Switzerland",
        "ci" to "Ivory Coast",
        "ck" to "Cook Islands",
        "cl" to "Chile",
        "cm" to "Cameroon",
        "cn" to "China",
        "co" to "Colombia",
        "cr" to "Costa Rica",
        "cu" to "Cuba",
        "cv" to "Cape Verde",
        "cw" to "Curaçao",
        "cx" to "Christmas Island",
        "cy" to "Cyprus",
        "cz" to "Czech Republic",
        "de" to "Germany",
        "dj" to "Djibouti",
        "dk" to "Denmark",
        "dm" to "Dominica",
        "do" to "Dominican Republic",
        "dz" to "Algeria",
        "ec" to "Ecuador",
        "ee" to "Estonia",
        "eg" to "Egypt",
        "eh" to "Western Sahara",
        "er" to "Eritrea",
        "es" to "Spain",
        "et" to "Ethiopia",
        "fi" to "Finland",
        "fj" to "Fiji",
        "fm" to "Micronesia",
        "fo" to "Faroe Islands",
        "fr" to "France",
        "ga" to "Gabon",
        "gb" to "United Kingdom",
        "gd" to "Grenada",
        "ge" to "Georgia",
        "gf" to "French Guiana",
        "gg" to "Guernsey",
        "gh" to "Ghana",
        "gi" to "Gibraltar",
        "gl" to "Greenland",
        "gm" to "Gambia",
        "gn" to "Guinea",
        "gp" to "Guadeloupe",
        "gq" to "Equatorial Guinea",
        "gr" to "Greece",
        "gt" to "Guatemala",
        "gu" to "Guam",
        "gw" to "Guinea-Bissau",
        "gy" to "Guyana",
        "hk" to "Hong Kong",
        "hm" to "Heard Island and McDonald Islands",
        "hn" to "Honduras",
        "hr" to "Croatia",
        "ht" to "Haiti",
        "hu" to "Hungary",
        "id" to "Indonesia",
        "ie" to "Ireland",
        "il" to "Israel",
        "im" to "Isle of Man",
        "in" to "India",
        "io" to "British Indian Ocean Territory",
        "iq" to "Iraq",
        "ir" to "Iran",
        "is" to "Iceland",
        "it" to "Italy",
        "je" to "Jersey",
        "jm" to "Jamaica",
        "jo" to "Jordan",
        "jp" to "Japan",
        "ke" to "Kenya",
        "kg" to "Kyrgyzstan",
        "kh" to "Cambodia",
        "ki" to "Kiribati",
        "km" to "Comoros",
        "kn" to "Saint Kitts and Nevis",
        "kp" to "North Korea",
        "kr" to "South Korea",
        "kw" to "Kuwait",
        "ky" to "Cayman Islands",
        "kz" to "Kazakhstan",
        "la" to "Laos",
        "lb" to "Lebanon",
        "lc" to "Saint Lucia",
        "li" to "Liechtenstein",
        "lk" to "Sri Lanka",
        "lr" to "Liberia",
        "ls" to "Lesotho",
        "lt" to "Lithuania",
        "lu" to "Luxembourg",
        "lv" to "Latvia",
        "ly" to "Libya",
        "ma" to "Morocco",
        "mc" to "Monaco",
        "md" to "Moldova",
        "me" to "Montenegro",
        "mf" to "Saint Martin",
        "mg" to "Madagascar",
        "mh" to "Marshall Islands",
        "mk" to "North Macedonia",
        "ml" to "Mali",
        "mm" to "Myanmar",
        "mn" to "Mongolia",
        "mo" to "Macau",
        "mp" to "Northern Mariana Islands",
        "mq" to "Martinique",
        "mr" to "Mauritania",
        "ms" to "Montserrat",
        "mt" to "Malta",
        "mu" to "Mauritius",
        "mv" to "Maldives",
        "mw" to "Malawi",
        "mx" to "Mexico",
        "my" to "Malaysia",
        "mz" to "Mozambique",
        "na" to "Namibia",
        "nc" to "New Caledonia",
        "ne" to "Niger",
        "nf" to "Norfolk Island",
        "ng" to "Nigeria",
        "ni" to "Nicaragua",
        "nl" to "Netherlands",
        "no" to "Norway",
        "np" to "Nepal",
        "nr" to "Nauru",
        "nu" to "Niue",
        "nz" to "New Zealand",
        "om" to "Oman",
        "pa" to "Panama",
        "pe" to "Peru",
        "pf" to "French Polynesia",
        "pg" to "Papua New Guinea",
        "ph" to "Philippines",
        "pk" to "Pakistan",
        "pl" to "Poland",
        "pm" to "Saint Pierre and Miquelon",
        "pn" to "Pitcairn Islands",
        "pr" to "Puerto Rico",
        "pt" to "Portugal",
        "pw" to "Palau",
        "py" to "Paraguay",
        "qa" to "Qatar",
        "re" to "Réunion",
        "ro" to "Romania",
        "rs" to "Serbia",
        "ru" to "Russia",
        "rw" to "Rwanda",
        "sa" to "Saudi Arabia",
        "sb" to "Solomon Islands",
        "sc" to "Seychelles",
        "sd" to "Sudan",
        "se" to "Sweden",
        "sg" to "Singapore",
        "sh" to "Saint Helena",
        "si" to "Slovenia",
        "sj" to "Svalbard and Jan Mayen",
        "sk" to "Slovakia",
        "sl" to "Sierra Leone",
        "sm" to "San Marino",
        "sn" to "Senegal",
        "so" to "Somalia",
        "sr" to "Suriname",
        "ss" to "South Sudan",
        "st" to "Sao Tome and Principe",
        "sv" to "El Salvador",
        "sx" to "Sint Maarten",
        "sy" to "Syria",
        "sz" to "Eswatini",
        "tc" to "Turks and Caicos Islands",
        "td" to "Chad",
        "tf" to "French Southern Territories",
        "tg" to "Togo",
        "th" to "Thailand",
        "tj" to "Tajikistan",
        "tk" to "Tokelau",
        "tl" to "Timor-Leste",
        "tm" to "Turkmenistan",
        "tn" to "Tunisia",
        "to" to "Tonga",
        "tr" to "Turkey",
        "tt" to "Trinidad and Tobago",
        "tv" to "Tuvalu",
        "tz" to "Tanzania",
        "ua" to "Ukraine",
        "ug" to "Uganda",
        "um" to "U.S. Minor Outlying Islands",
        "us" to "United States",
        "uy" to "Uruguay",
        "uz" to "Uzbekistan",
        "va" to "Vatican City",
        "vc" to "Saint Vincent and the Grenadines",
        "ve" to "Venezuela",
        "vg" to "British Virgin Islands",
        "vi" to "U.S. Virgin Islands",
        "vn" to "Vietnam",
        "vu" to "Vanuatu",
        "wf" to "Wallis and Futuna",
        "ws" to "Samoa",
        "ye" to "Yemen",
        "yt" to "Mayotte",
        "za" to "South Africa",
        "zm" to "Zambia",
        "zw" to "Zimbabwe"
    )

    private val flagMap = mapOf(
        "ad" to R.drawable.flag_ad,
        "ae" to R.drawable.flag_ae,
        "af" to R.drawable.flag_af,
        "ag" to R.drawable.flag_ag,
        "ai" to R.drawable.flag_ai,
        "al" to R.drawable.flag_al,
        "am" to R.drawable.flag_am,
        "ao" to R.drawable.flag_ao,
        "aq" to R.drawable.flag_aq,
        "ar" to R.drawable.flag_ar,
        "arab" to R.drawable.flag_arab,
        "as" to R.drawable.flag_as,
        "asean" to R.drawable.flag_asean,
        "at" to R.drawable.flag_at,
        "au" to R.drawable.flag_au,
        "aw" to R.drawable.flag_aw,
        "ax" to R.drawable.flag_ax,
        "az" to R.drawable.flag_az,
        "ba" to R.drawable.flag_ba,
        "bb" to R.drawable.flag_bb,
        "bd" to R.drawable.flag_bd,
        "be" to R.drawable.flag_be,
        "bf" to R.drawable.flag_bf,
        "bg" to R.drawable.flag_bg,
        "bh" to R.drawable.flag_bh,
        "bi" to R.drawable.flag_bi,
        "bj" to R.drawable.flag_bj,
        "bl" to R.drawable.flag_bl,
        "bm" to R.drawable.flag_bm,
        "bn" to R.drawable.flag_bn,
        "bo" to R.drawable.flag_bo,
        "bq" to R.drawable.flag_bq,
        "br" to R.drawable.flag_br,
        "bs" to R.drawable.flag_bs,
        "bt" to R.drawable.flag_bt,
        "bv" to R.drawable.flag_bv,
        "bw" to R.drawable.flag_bw,
        "by" to R.drawable.flag_by,
        "bz" to R.drawable.flag_bz,
        "ca" to R.drawable.flag_ca,
        "cc" to R.drawable.flag_cc,
        "cd" to R.drawable.flag_cd,
        "cefta" to R.drawable.flag_cefta,
        "cf" to R.drawable.flag_cf,
        "cg" to R.drawable.flag_cg,
        "ch" to R.drawable.flag_ch,
        "ci" to R.drawable.flag_ci,
        "ck" to R.drawable.flag_ck,
        "cl" to R.drawable.flag_cl,
        "cm" to R.drawable.flag_cm,
        "cn" to R.drawable.flag_cn,
        "co" to R.drawable.flag_co,
        "cp" to R.drawable.flag_cp,
        "cr" to R.drawable.flag_cr,
        "cu" to R.drawable.flag_cu,
        "cv" to R.drawable.flag_cv,
        "cw" to R.drawable.flag_cw,
        "cx" to R.drawable.flag_cx,
        "cy" to R.drawable.flag_cy,
        "cz" to R.drawable.flag_cz,
        "de" to R.drawable.flag_de,
        "dg" to R.drawable.flag_dg,
        "dj" to R.drawable.flag_dj,
        "dk" to R.drawable.flag_dk,
        "dm" to R.drawable.flag_dm,
        "do" to R.drawable.flag_do,
        "dz" to R.drawable.flag_dz,
        "eac" to R.drawable.flag_eac,
        "ec" to R.drawable.flag_ec,
        "ee" to R.drawable.flag_ee,
        "eg" to R.drawable.flag_eg,
        "eh" to R.drawable.flag_eh,
        "er" to R.drawable.flag_er,
        "es" to R.drawable.flag_es,
        "es_ct" to R.drawable.flag_es_ct,
        "es_ga" to R.drawable.flag_es_ga,
        "es_pv" to R.drawable.flag_es_pv,
        "et" to R.drawable.flag_et,
        "eu" to R.drawable.flag_eu,
        "fi" to R.drawable.flag_fi,
        "fj" to R.drawable.flag_fj,
        "fk" to R.drawable.flag_fk,
        "fm" to R.drawable.flag_fm,
        "fo" to R.drawable.flag_fo,
        "fr" to R.drawable.flag_fr,
        "ga" to R.drawable.flag_ga,
        "gb" to R.drawable.flag_gb,
        "gb_eng" to R.drawable.flag_gb_eng,
        "gb_nir" to R.drawable.flag_gb_nir,
        "gb_sct" to R.drawable.flag_gb_sct,
        "gb_wls" to R.drawable.flag_gb_wls,
        "gd" to R.drawable.flag_gd,
        "ge" to R.drawable.flag_ge,
        "gf" to R.drawable.flag_gf,
        "gg" to R.drawable.flag_gg,
        "gh" to R.drawable.flag_gh,
        "gi" to R.drawable.flag_gi,
        "gl" to R.drawable.flag_gl,
        "gm" to R.drawable.flag_gm,
        "gn" to R.drawable.flag_gn,
        "gp" to R.drawable.flag_gp,
        "gq" to R.drawable.flag_gq,
        "gr" to R.drawable.flag_gr,
        "gs" to R.drawable.flag_gs,
        "gt" to R.drawable.flag_gt,
        "gu" to R.drawable.flag_gu,
        "gw" to R.drawable.flag_gw,
        "gy" to R.drawable.flag_gy,
        "hk" to R.drawable.flag_hk,
        "hm" to R.drawable.flag_hm,
        "hn" to R.drawable.flag_hn,
        "hr" to R.drawable.flag_hr,
        "ht" to R.drawable.flag_ht,
        "hu" to R.drawable.flag_hu,
        "ic" to R.drawable.flag_ic,
        "id" to R.drawable.flag_id,
        "ie" to R.drawable.flag_ie,
        "il" to R.drawable.flag_il,
        "im" to R.drawable.flag_im,
        "in" to R.drawable.flag_in,
        "io" to R.drawable.flag_io,
        "iq" to R.drawable.flag_iq,
        "ir" to R.drawable.flag_ir,
        "is" to R.drawable.flag_is,
        "it" to R.drawable.flag_it,
        "je" to R.drawable.flag_je,
        "jm" to R.drawable.flag_jm,
        "jo" to R.drawable.flag_jo,
        "jp" to R.drawable.flag_jp,
        "ke" to R.drawable.flag_ke,
        "kg" to R.drawable.flag_kg,
        "kh" to R.drawable.flag_kh,
        "ki" to R.drawable.flag_ki,
        "km" to R.drawable.flag_km,
        "kn" to R.drawable.flag_kn,
        "kp" to R.drawable.flag_kp,
        "kr" to R.drawable.flag_kr,
        "kw" to R.drawable.flag_kw,
        "ky" to R.drawable.flag_ky,
        "kz" to R.drawable.flag_kz,
        "la" to R.drawable.flag_la,
        "lb" to R.drawable.flag_lb,
        "lc" to R.drawable.flag_lc,
        "li" to R.drawable.flag_li,
        "lk" to R.drawable.flag_lk,
        "lr" to R.drawable.flag_lr,
        "ls" to R.drawable.flag_ls,
        "lt" to R.drawable.flag_lt,
        "lu" to R.drawable.flag_lu,
        "lv" to R.drawable.flag_lv,
        "ly" to R.drawable.flag_ly,
        "ma" to R.drawable.flag_ma,
        "mc" to R.drawable.flag_mc,
        "md" to R.drawable.flag_md,
        "me" to R.drawable.flag_me,
        "mf" to R.drawable.flag_mf,
        "mg" to R.drawable.flag_mg,
        "mh" to R.drawable.flag_mh,
        "mk" to R.drawable.flag_mk,
        "ml" to R.drawable.flag_ml,
        "mm" to R.drawable.flag_mm,
        "mn" to R.drawable.flag_mn,
        "mo" to R.drawable.flag_mo,
        "mp" to R.drawable.flag_mp,
        "mq" to R.drawable.flag_mq,
        "mr" to R.drawable.flag_mr,
        "ms" to R.drawable.flag_ms,
        "mt" to R.drawable.flag_mt,
        "mu" to R.drawable.flag_mu,
        "mv" to R.drawable.flag_mv,
        "mw" to R.drawable.flag_mw,
        "mx" to R.drawable.flag_mx,
        "my" to R.drawable.flag_my,
        "mz" to R.drawable.flag_mz,
        "na" to R.drawable.flag_na,
        "nc" to R.drawable.flag_nc,
        "ne" to R.drawable.flag_ne,
        "nf" to R.drawable.flag_nf,
        "ng" to R.drawable.flag_ng,
        "ni" to R.drawable.flag_ni,
        "nl" to R.drawable.flag_nl,
        "no" to R.drawable.flag_no,
        "np" to R.drawable.flag_np,
        "nr" to R.drawable.flag_nr,
        "nu" to R.drawable.flag_nu,
        "nz" to R.drawable.flag_nz,
        "om" to R.drawable.flag_om,
        "pa" to R.drawable.flag_pa,
        "pc" to R.drawable.flag_pc,
        "pe" to R.drawable.flag_pe,
        "pf" to R.drawable.flag_pf,
        "pg" to R.drawable.flag_pg,
        "ph" to R.drawable.flag_ph,
        "pk" to R.drawable.flag_pk,
        "pl" to R.drawable.flag_pl,
        "pm" to R.drawable.flag_pm,
        "pn" to R.drawable.flag_pn,
        "pr" to R.drawable.flag_pr,
        "ps" to R.drawable.flag_ps,
        "pt" to R.drawable.flag_pt,
        "pw" to R.drawable.flag_pw,
        "py" to R.drawable.flag_py,
        "qa" to R.drawable.flag_qa,
        "re" to R.drawable.flag_re,
        "ro" to R.drawable.flag_ro,
        "rs" to R.drawable.flag_rs,
        "ru" to R.drawable.flag_ru,
        "rw" to R.drawable.flag_rw,
        "sa" to R.drawable.flag_sa,
        "sb" to R.drawable.flag_sb,
        "sc" to R.drawable.flag_sc,
        "sd" to R.drawable.flag_sd,
        "se" to R.drawable.flag_se,
        "sg" to R.drawable.flag_sg,
        "sh" to R.drawable.flag_sh,
        "sh_ac" to R.drawable.flag_sh_ac,
        "sh_hl" to R.drawable.flag_sh_hl,
        "sh_ta" to R.drawable.flag_sh_ta,
        "si" to R.drawable.flag_si,
        "sj" to R.drawable.flag_sj,
        "sk" to R.drawable.flag_sk,
        "sl" to R.drawable.flag_sl,
        "sm" to R.drawable.flag_sm,
        "sn" to R.drawable.flag_sn,
        "so" to R.drawable.flag_so,
        "sr" to R.drawable.flag_sr,
        "ss" to R.drawable.flag_ss,
        "st" to R.drawable.flag_st,
        "sv" to R.drawable.flag_sv,
        "sx" to R.drawable.flag_sx,
        "sy" to R.drawable.flag_sy,
        "sz" to R.drawable.flag_sz,
        "tc" to R.drawable.flag_tc,
        "td" to R.drawable.flag_td,
        "tf" to R.drawable.flag_tf,
        "tg" to R.drawable.flag_tg,
        "th" to R.drawable.flag_th,
        "tj" to R.drawable.flag_tj,
        "tk" to R.drawable.flag_tk,
        "tl" to R.drawable.flag_tl,
        "tm" to R.drawable.flag_tm,
        "tn" to R.drawable.flag_tn,
        "to" to R.drawable.flag_to,
        "tr" to R.drawable.flag_tr,
        "tt" to R.drawable.flag_tt,
        "tv" to R.drawable.flag_tv,
        "tw" to R.drawable.flag_tw,
        "tz" to R.drawable.flag_tz,
        "ua" to R.drawable.flag_ua,
        "ug" to R.drawable.flag_ug,
        "um" to R.drawable.flag_um,
        "un" to R.drawable.flag_un,
        "us" to R.drawable.flag_us,
        "uy" to R.drawable.flag_uy,
        "uz" to R.drawable.flag_uz,
        "va" to R.drawable.flag_va,
        "vc" to R.drawable.flag_vc,
        "ve" to R.drawable.flag_ve,
        "vg" to R.drawable.flag_vg,
        "vi" to R.drawable.flag_vi,
        "vn" to R.drawable.flag_vn,
        "vu" to R.drawable.flag_vu,
        "wf" to R.drawable.flag_wf,
        "ws" to R.drawable.flag_ws,
        "xk" to R.drawable.flag_xk,
        "xx" to R.drawable.flag_xx,
        "ye" to R.drawable.flag_ye,
        "yt" to R.drawable.flag_yt,
        "za" to R.drawable.flag_za,
        "zm" to R.drawable.flag_zm,
        "zw" to R.drawable.flag_zw
    )
}