name: Update VPNGate CSV

on:
  workflow_dispatch:          # ✅ позволяет вручную запускать
  schedule:
    - cron: '*/30 * * * *'    # ✅ Обновление каждые 30 минут

permissions:
  contents: write             # ✅ позволяет делать git push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download VPNGate CSV
        run: |
          curl -s https://www.vpngate.net/api/iphone/ -o app/src/main/assets/vpngate.csv

      - name: Commit and push if changed
        uses: EndBug/add-and-commit@v9
        with:
          message: "Auto-update VPNGate CSV"
          add: "app/src/main/assets/vpngate.csv"